baseURL = "https://saiyamjain.in"
title = "My Portfolio"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # name to display as main title
    mainpagetitle = "Saiyam Jain"

    # subtitle to display under the title
    mainpagesubtitle = "SKILLS" 

    # description of website
    mainpagedesc = "> HTML, JavaScript, CSS, SASS and many under development"

    # name to display in the copyright section in the footer
    copyrightname = ""

    # url to use as link in the copyright name in the footer
    copyrighturl = ""

    # Urls for social networks
    # linkedin = "http://www.linkedin.com/in/saiyameh"
    # github = "https://github.com/saiyameh"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 0.8

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Copyright"
    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""
    # Text to go before copyright information
    prefix = ""
    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"       # The path can lead to a content folder too.
    weight = 30
[taxonomies]
category = "categories"
tag = "tags"

# [privacy]

#   [privacy.vimeo]
#     disabled = false
#     simple = true

#   [privacy.twitter]
#     disabled = false
#     enableDNT = true
#     simple = true

#   [privacy.instagram]
#     disabled = false
#     simple = true

#   [privacy.youtube]
#     disabled = false
#     privacyEnhanced = true

# [services]

#   [services.instagram]
#     disableInlineCSS = true

#   [services.twitter]
#     disableInlineCSS = true